# Server Name Settings
# Here you must put the name of your server, which will be placed in several 
# places within your server automatically
server-name: "§6HolyPvP"

floating: "5:66:0"

shopfloating: "20:65:0"

WebhookGamemodeLogs: "https://discord.com/api/webhooks/936993532089098372/ZfGMMgw9xcanBZokNxpG6bxUzwRwOSy4h6o34a60wdRjAzNqa9cuzfMWZHHpugrkjFOC"

# Server Info Settins
# Here you must add all the data of your server, this data will be shown in a 
# default message to the players when entering the server
server-storelink: "store.holypvp.net"
server-twitterlink: "twitter.com/holypvpnet" #Los mensajes automaticos agarran automaticamente los datos de la store, no neceistan editar nada del codigo, unicamente la config a su gusto :*
server-tslink: "ts.holypvp.net"
server-discordlink: "discord.gg/holypvp"

# Server MOTD Settings
# Server custom MOTD, here we can edit the MOTD of your server and put what you like
server-motd: "&6&lHoly &r&f| &7Hub"

# Servers Settings

#HCF Settings
HCF-NAME: §r§l§6HCF §r§a*$50 PAYPAL*
HCF-IP: greekmc.net
HCF-PORT: 19132
#KITMAP Settings
KITMAP-NAME: §r§l§6Kits
KITMAP-IP: greekmc.net
KITMAP-PORT: 19132
#PRACTICE Settings
PRACTICE-NAME: §r§l§6Practice
PRACTICE-IP: greekmc.net
PRACTICE-PORT: 19132

# ScoreBoard Settings
# Here you can configure the scoreboard, from the title to the lines you want them 
# to have, you can use {players_count}, {player_ping}, {player_nick} to further 
# customize your scoreboard
scoreboard.title: "§r§c♥ §6§lHolyPvP §r§c♥"
scoreboard.lines:
  - '&7'
  - ' &6Rank:'
  - ' §r§fDefault'
  - '&7&r&b'
  - ' &6Online:'
  - ' §r§f{players_count}'
  - '&7&r'
  - ' &7&oholypvp.net'
  - '&7&r'



